modLoader = "javafml"
loaderVersion= "[32,)"
license = "MIT"

[[mods]]
modId = "armorhotswap"
version = "1.9"
displayName = "Armor Hotswap"
displayURL= "https://www.curseforge.com/minecraft/mc-mods/armor-hotswap"
issueTrackerURL = "https://github.com/kregerl/armorhotswap/issues"
logoFile = "ArmorHotswapLogo.png"
credits =""
authors = "AreUThreateningMe"
description = '''
	Right click while holding a piece of armor to swap it with the currently equipped armor'''
[[dependencies.armorhotswap]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.armorhotswap]]
modId = "minecraft"
mandatory= true
versionRange = "[1.16.1, 1.16.5]"
ordering = "AFTER"
side ="BOTH"
